FROM aurelbruno06/consul_base
MAINTAINER Aurelien Bruno <aurelbruno06@gmail.com>
RUN echo "v1.0.14" > /tmp/version
ADD https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_web_ui.zip /tmp/consul_0.6.4_web_ui.zip
RUN unzip  /tmp/consul_0.6.4_web_ui.zip -d /etc/consul && rm  /tmp/consul_0.6.4_web_ui.zip
ADD consul.d /etc/consul.d
ADD start.sh /root/
#ADD init/consul.conf /etc/init/consul.conf
ENTRYPOINT ["/root/start.sh"]
EXPOSE 8300 8301 8301/udp 8302 8302/udp 8400 8500 53/udp

