FROM ubuntu:16.04
MAINTAINER Aurelien Bruno <aurelbruno06@gmail.com>
RUN apt-get update && apt-get -y install openjdk-8-jdk wget openssh-server openssh-client net-tools openssl rsync bzip2 unzip && rm -rf /var/lib/apt/lists/*
